// ─── Global Styles ────────────────────────────────────────────────────────────
export const S = {
  root: {
    minHeight: '100vh',
    background: '#f0f2f5',
    fontFamily: "'Inter', system-ui, sans-serif",
    color: '#1a2035',
  },
  navbar: {
    background: '#fff',
    borderBottom: '1px solid #e3e8ef',
    display: 'flex',
    alignItems: 'center',
    padding: '0 32px',
    height: 56,
    position: 'sticky',
    top: 0,
    zIndex: 100,
    boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginRight: 40,
  },
  brandDot: {
    width: 28,
    height: 28,
    borderRadius: 8,
    background: 'linear-gradient(135deg, #1a56db, #4f83f7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: '-0.5px',
  },
  brandName: {
    fontSize: 15,
    fontWeight: 700,
    color: '#1a2035',
    letterSpacing: '-0.3px',
  },
  navTabs: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    flex: 1,
  },
  navTab: (active) => ({
    padding: '6px 16px',
    borderRadius: 6,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: active ? 600 : 400,
    color: active ? '#1a56db' : '#64748b',
    background: active ? '#eff6ff' : 'transparent',
    border: 'none',
    outline: 'none',
    transition: 'all 0.15s',
    userSelect: 'none',
    whiteSpace: 'nowrap',
  }),
  navRight: {
    display: 'flex',
    alignItems: 'center',
    marginLeft: 'auto',
  },
  badge: {
    background: '#eff6ff',
    color: '#1a56db',
    fontSize: 11,
    fontWeight: 600,
    padding: '3px 10px',
    borderRadius: 20,
    border: '1px solid #bfdbfe',
  },
  page: {
    padding: '28px 32px',
    maxWidth: 1400,
    margin: '0 auto',
  },
  pageHeader: {
    marginBottom: 24,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: '#1a2035',
    letterSpacing: '-0.3px',
  },
  pageSub: {
    fontSize: 13,
    color: '#64748b',
    marginTop: 2,
  },
  grid4: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: 16,
    marginBottom: 20,
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 16,
    marginBottom: 20,
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 16,
    marginBottom: 20,
  },
  card: {
    background: '#fff',
    borderRadius: 10,
    border: '1px solid #e3e8ef',
    padding: '20px 24px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
    marginBottom: 20,
  },
  kpiCard: {
    background: '#fff',
    borderRadius: 10,
    border: '1px solid #e3e8ef',
    padding: '18px 20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
    position: 'relative',
    overflow: 'hidden',
  },
  kpiAccent: (color) => ({
    position: 'absolute',
    top: 0, right: 0,
    width: 4,
    height: '100%',
    background: color,
    borderRadius: '0 10px 10px 0',
  }),
  kpiLabel: {
    fontSize: 11,
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: '0.7px',
    fontWeight: 600,
    marginBottom: 6,
  },
  kpiValue: {
    fontSize: 26,
    fontWeight: 800,
    letterSpacing: '-1px',
    color: '#1a2035',
  },
  kpiSub: {
    fontSize: 12,
    color: '#94a3b8',
    marginTop: 4,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: '#1a2035',
    marginBottom: 16,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 13,
  },
  th: {
    textAlign: 'left',
    padding: '8px 12px',
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    borderBottom: '1px solid #f1f5f9',
    background: '#f8fafc',
  },
  td: {
    padding: '10px 12px',
    borderBottom: '1px solid #f1f5f9',
    color: '#334155',
  },
  pill: (color) => ({
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 600,
    background: color === 'green'  ? '#f0fdf4' :
                color === 'red'    ? '#fef2f2' :
                color === 'yellow' ? '#fffbeb' : '#eff6ff',
    color:      color === 'green'  ? '#16a34a' :
                color === 'red'    ? '#dc2626' :
                color === 'yellow' ? '#d97706' : '#1a56db',
    border: `1px solid ${
                color === 'green'  ? '#bbf7d0' :
                color === 'red'    ? '#fecaca' :
                color === 'yellow' ? '#fde68a' : '#bfdbfe'}`,
  }),
  placeholder: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: 180,
    gap: 8,
    border: '2px dashed #e2e8f0',
    borderRadius: 8,
    background: '#f8fafc',
  },
  loadingWrap: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '60vh',
    flexDirection: 'column',
    gap: 12,
    color: '#64748b',
    fontSize: 14,
  },
}
